# config/services.yaml
services:
    LdH\Service\PeopleService:
        public: true

    LdH\Service\CardService:
        public: true

    LdH\Service\MapService:
        public: true

    LdH\Service\StateService:
        public: true

    # Repositories
    LdH\Repository\MapRepository:
        public: true

    LdH\Repository\CardRepository:
        public: true

    # States
    LdH\State\AbstractState:
        public: true

    LdH\State\GameInitState:
        public: true
        tags: ['ldh.state']

    LdH\State\ChooseLineageState:
        public: true
        tags: [ 'ldh.state' ]

    LdH\State\DrawObjectiveState:
        public: true
        tags: ['ldh.state']

    LdH\State\DeadEndState:
        public: true
        tags: ['ldh.state']