# config/services.yaml
services:
    LdH\Service\BonusService:
        public: true

    LdH\Service\PeopleService:
        public: true

    LdH\Service\CardService:
        public: true

    LdH\Service\MapService:
        public: true

    LdH\Service\StateService:
        public: true

    LdH\Repository\Field:
        public: true

    # States
    LdH\State\AbstractState:
        public: true

    LdH\State\GameInitState:
        public: true
        tags: ['ldh.state']

    LdH\State\ChooseLineageState:
        public: true
        tags: [ 'ldh.state' ]

    LdH\State\GameStartState:
        public: true
        tags: ['ldh.state']

    LdH\State\PrincipalState:
        public: true
        tags: ['ldh.state']

    LdH\State\PreparePrincipalState:
        public: true
        tags: ['ldh.state']

    LdH\State\EndTurnState:
        public: true
        tags: [ 'ldh.state' ]

    LdH\State\DeadEndState:
        public: true
        tags: ['ldh.state']

    LdH\State\EndOfEndTurnState:
        public: true
        tags: ['ldh.state']

    LdH\State\FoodHarvestBonusState:
        public: true
        tags: ['ldh.state']

    LdH\State\FoodHarvestState:
        public: true
        tags: ['ldh.state']

    LdH\State\ScienceHarvestBonusState:
        public: true
        tags: ['ldh.state']

    LdH\State\ScienceHarvestState:
        public: true
        tags: ['ldh.state']

